version: "3.7"

services:
  hypotheses:
    build:
      context: ./repos/hypotheses
    env_file:
      - docker.env
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/hypotheses
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: hypotheses
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  # NGINX + CERTBOT
  # frontend:
  #   image: staticfloat/nginx-certbot
  #   ports:
  #     - 80:80/tcp
  #     - 443:443/tcp
  #   environment:
  #     CERTBOT_EMAIL: ${CERTBOT_EMAIL}
  #     ENVSUBST_VARS: HPTH_URL HPTH_PORT
  #     HPTH_URL: ${HPTH_URL}
  #     HPTH_PORT: ${HPTH_PORT}
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx:/etc/nginx/user.conf.d:ro
  #     - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt:
  pgdata: