# Author: Anicet Nougaret
# =======================
# Requirements :
#  - clone https://github.com/AnicetNgrt/hypotheses.io to ./repos/hypotheses
#  - clone https://github.com/Homesynck/Homesynck-server to ./repos/homesynck
#  - clone https://github.com/AnicetNgrt/anicetnougaret.fr to ./repos/an_site
# =======================

version: "3.7"

services:
  anicet-portfolio:
    build:
      context: ./repos/an_site
    ports:
      - "8080:8080"
    restart: always

  anicet-pjs4-homesynck:
    build:
      context: ./repos/homesynck/homesynck
    env_file:
      - docker.env
    environment:
      DATABASE_URL: ecto://postgres:postgres@anicet-postgre/homesynck
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: homesynck
      DATABASE_PORT: 5432
      DATABASE_HOST: anicet-postgre
      ENABLE_ADMIN_ACCOUNT: "true"
      ENABLE_REGISTER: "false"
      ENABLE_SESSIONS: "true"
      ENABLE_PHONE_VALIDATION: "false"
      INSTANCE_NAME: "anicetnougaret.fr"
      INSTANCE_DESCRIPTION: "The main Homesynck node"
      INSTANCE_OWNER: "Homesynck team"
      HOST: homesynck.anicetnougaret.fr
      PORT: 4001
    ports:
      - "4001:4001"
    restart: always
    depends_on:
      - anicet-postgre
  
  anicet-fakebusters:
    build:
      context: ./repos/bourse2021/
    env_file:
      - docker.env
    environment:
      DATABASE_URL: ecto://postgres:postgres@anicet-postgre/fakebusters
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: fakebusters
      DATABASE_PORT: 5432
      DATABASE_HOST: anicet-postgre
      HOST: bourse2021-coddity.anicetnougaret.fr
      PORT: 4000
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - anicet-postgre
  anicet-postgre:
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    #volumes:
    #  - pgdata:/var/lib/postgresql/data
  # NGINX + CERTBOT
  anicet-nginx-certbot:
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: an.nougaret@gmail.com
      ENVSUBST_VARS: FKBT_U FKBT_P FKBT_H HMSK_U HMSK_P HMSK_H ANST_H ANST_U ANST_P
      FKBT_H: anicet-fakebusters
      FKBT_U: bourse2021-coddity.anicetnougaret.fr
      FKBT_P: 4000
      HMSK_H: anicet-pjs4-homesynck
      HMSK_U: homesynck.anicetnougaret.fr
      HMSK_P: 4001
      ANST_H: anicet-portfolio
      ANST_U: anicetnougaret.fr
      ANST_P: 8080
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt: