version: "3.7"

services:
  anicet-hypotheses:
    build:
      context: ./repos/hypotheses
    env_file:
      - docker.env
    environment:
      DATABASE_URL: ecto://postgres:postgres@anicet-postgre/hypotheses
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: hypotheses
      DATABASE_PORT: 5432
      DATABASE_HOST: anicet-postgre
      PORT: 4000
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - anicet-postgre
  anicet-postgre:
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    #volumes:
    #  - pgdata:/var/lib/postgresql/data
  # NGINX + CERTBOT
  anicet-nginx-certbot:
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: an.nougaret@gmail.com
      ENVSUBST_VARS: HPTH_URL HPTH_PORT HPTH_HOST
      HPTH_HOST: anicet-hypotheses
      HPTH_URL: bourse2021-coddity.anicetnougaret.fr
      HPTH_PORT: 4000
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt: